dataset:
  _target_: torchvision.datasets.CIFAR10
  root: cifar10
train:
  optimizer:
    _target_: torch.optim.Adam
    lr: 0.01
  loop:
    batch_size: 1048
    num_workers: 2
    num_epochs: 150
  augmentations:
  - _target_: torchvision.transforms.RandomHorizontalFlip
    p: 0.5
  save:
    model_directory: saved_models/
    samples_directory: train_samples/
    samples_frequency_epochs: 1
  wandb:
    project: diffusion_hw_1
    run_name: dvc
model:
  _target_: modeling.diffusion.DiffusionModel
  eps_model:
    _target_: modeling.unet.UnetModel
    in_channels: 3
    out_channels: 3
    hidden_size: 128
  betas:
  - 0.0001
  - 0.02
  num_timesteps: 1000
