stages:
  prepare_dataset:
    cmd: ./load_dataset.py
    deps:
      - load_dataset.py
      - configs/dataset/cifar10.yaml
    outs:
      - cifar10/
  train:
    cmd: ./train.py
    deps:
      - train.py
      - modeling/
      - cifar10/
      - configs/
    outs:
      - saved_models/
